# Generated by Django 5.0 on 2024-03-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="join_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.IntegerField(null=True),
        ),
    ]
